"""
Django settings for cbsfile project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gk=384+%=505y0dx3s8#9sg#ozm@clq41t4-xug6u)p1k7x5q^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cbfileapp',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cbsfile.urls'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server (e.g., Gmail, Outlook, etc.)
EMAIL_PORT = 587  # SMTP port (TLS: 587, SSL: 465)
EMAIL_USE_TLS = True  # Use TLS encryption (recommended)
EMAIL_HOST_USER = 'dece.nas.system@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'qryu golh eimk guer'  # Your email password (use App Passwords for Gmail)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


NETWORK_DRIVE = {
    "drive_letter": "Z:",
    "network_path": "\\\\172.16.127.120\\shared_folder",
     "username": os.getenv("NETWORK_USERNAME", "truenas_admin"),
     "password": os.getenv("NETWORK_PASSWORD", "@dece@"),
     "persistent": True,
}
# Allow iframe embedding for PDF files
X_FRAME_OPTIONS = "SAMEORIGIN"  # Allow iframes from the same site


# NETWORK_DRIVE = {
#     "drive_letter": "Z:",
#     "network_path": "\\192.168.102.219\nastry",
#     "persistent": True,
# }


MEDIA_ROOT = "Z:/"
MEDIA_URL = "/media/"



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cbsfile.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'deenas',  # Database name
        'USER': 'root',           # Default XAMPP MySQL user
        'PASSWORD': '',           # No password by default in XAMPP
        'HOST': '127.0.0.1',      # localhost
        'PORT': '3306',           # Default MySQL port in XAMPP
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Optional: If you want to collect all static files in one directory
STATICFILES_DIRS = [
    BASE_DIR / "cbfileapp/static",  # Adjust this path if necessary
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
